[package]
name = "gen2"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-bedrock = "1.58.0"
aws-config = "1.1.7"
serde_json = "1.0.132"
tokio = { version = "1.39", features = ["full"] }

[[bin]]
name = "gen-2"
path = "./gen-2.rs"